
export const professions = {
  ['professionCategories.content']: [
    'professions.editor',
    'professions.journalist',
    'professions.musician',
    'professions.promoter',
    'professions.publisher',
    'professions.writer',
  ],
  ['professionCategories.crafting']: [
    'professions.artisan',
    'professions.artist',
    'professions.builder',
    'professions.fabricator',
    'professions.tinker',
  ],
  ['professionCategories.logistics']: [
    'professions.biker',
    'professions.courier',
    'professions.mover',
    'professions.scout',
  ],
  ['professionCategories.hospitality']: [
    'professions.bard',
    'professions.bnbHost',
    'professions.concierge',
    'professions.guide',
    'professions.jester',
  ],
  ['professionCategories.provisioning']: [
    'professions.baker',
    'professions.bartender',
    'professions.caterer',
    'professions.chef',
    'professions.farmer',
    'professions.herbalist',
    'professions.horticulurist',
    'professions.merchant',
  ],
  ['professionCategories.responders']: [
    'professions.constable',
    'professions.fighter',
    'professions.guardian',
    'professions.medic',
  ],
  ['professionCategories.services']: [
    'professions.caregiver',
    'professions.cleaner',
    'professions.nurse',
  ],
  ['professionCategories.specialists']: [
    'professions.architect',
    'professions.dancer',
    'professions.designer',
    'professions.engineer',
    'professions.entrepreneur',
    'professions.programmer',
    'professions.scholar',
    'professions.scientist',
    'professions.teacher',
    'professions.technician',
  ],
  ['professionCategories.various']: [
    'professions.cleric',
    'professions.druid',
    'professions.monk',
    'professions.ranger',
    'professions.shaman',
    'professions.wizard',
  ],
}
